# Generated by Django 4.2.7 on 2025-08-06 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('loyalty_points', models.PositiveIntegerField(default=0, verbose_name='Points de fidélité')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'ingrédient")),
                ('unit', models.CharField(max_length=50, verbose_name='Unité de mesure')),
                ('current_stock', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock actuel')),
                ('minimum_stock', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock minimum')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Coût par unité')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Fournisseur')),
                ('last_restocked', models.DateTimeField(blank=True, null=True, verbose_name='Dernier réapprovisionnement')),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaire',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du plat')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('preparation_time', models.PositiveIntegerField(help_text='Temps de préparation en minutes')),
                ('ingredients', models.TextField(blank=True, verbose_name='Ingrédients')),
                ('allergens', models.CharField(blank=True, max_length=500, verbose_name='Allergènes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Plat du menu',
                'verbose_name_plural': 'Plats du menu',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Numéro de table')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacité')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Emplacement')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('waiter', 'Serveur'), ('chef', 'Chef'), ('manager', 'Manager'), ('cashier', 'Caissier'), ('host', "Hôte d'accueil")], max_length=20, verbose_name='Rôle')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('hire_date', models.DateField(verbose_name="Date d'embauche")),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Salaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de commande')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('preparing', 'En préparation'), ('ready', 'Prête'), ('served', 'Servie'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Espèces'), ('card', 'Carte bancaire'), ('check', 'Chèque'), ('mobile', 'Paiement mobile')], max_length=20, verbose_name='Mode de paiement')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sous-total')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant TVA')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant total')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Remise')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('served_at', models.DateTimeField(blank=True, null=True, verbose_name='Heure de service')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Heure de paiement')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.customer', verbose_name='Client')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.table', verbose_name='Table')),
                ('waiter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.staff', verbose_name='Serveur')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Heure')),
                ('party_size', models.PositiveIntegerField(verbose_name='Nombre de personnes')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('seated', 'Installée'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('no_show', 'Absent')], default='pending', max_length=20, verbose_name='Statut')),
                ('special_requests', models.TextField(blank=True, verbose_name='Demandes spéciales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.customer', verbose_name='Client')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.table', verbose_name='Table')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['date', 'time'],
                'unique_together': {('table', 'date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix unitaire')),
                ('special_instructions', models.TextField(blank=True, verbose_name='Instructions spéciales')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.menuitem', verbose_name='Plat')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
                'unique_together': {('order', 'menu_item')},
            },
        ),
    ]
